AllCops:
  TargetRubyVersion: 3.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false
